package com.sad.architecture.annotation;

/**
 * Created by Administrator on 2019/3/20 0020.
 */

public class Constant {

    public static final String PACKAGE_SAD_ARCHITECTURE="com.sad.architecture";

    public static final String PACKAGE_SAD_ARCHITECTURE_API=PACKAGE_SAD_ARCHITECTURE+".api";

    public static final String PACKAGE_SAD_ARCHITECTURE_ANNOTATION=PACKAGE_SAD_ARCHITECTURE+".annotation";

    public static final String PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION=PACKAGE_SAD_ARCHITECTURE_API+".componentization";

    public static final String PACKAGE_SAD_ARCHITECTURE_API_INIT=PACKAGE_SAD_ARCHITECTURE_API+".init";

    public static final String PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION_COMPONENT_REGISTER=PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION+".component.register";

    public static final String PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION_INTERNAL=PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION+".internal";

    public static final String PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION_IMPL=PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION+".impl";

    public static final String PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION_IPC=PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION+".ipc";

    public static final String PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION_EXTENSION=PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION+".extension";

    public static final String PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION_EXTENSION_ROUTER=PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION_EXTENSION+".router";

    public static final String PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION_EXTENSION_ROUTER_ACTIVITY=PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION_EXTENSION_ROUTER+".activity";

    public static final String PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION_EXTENSION_ROUTER_SERVICE=PACKAGE_SAD_ARCHITECTURE_API_COMPONENTIZATION_EXTENSION_ROUTER+".service";



    /*public static final String PACKAGE_SAD_ARCHITECTURE_REGISTER=PACKAGE_SAD_ARCHITECTURE+".register";

    public static final String PACKAGE_SAD_ARCHITECTURE_REGISTER_APPARCHITECTURE=PACKAGE_SAD_ARCHITECTURE_REGISTER+".appARCHITECTURE";

    public final static String PACKAGE_SAD_ARCHITECTURE_REGISTER_IPC=PACKAGE_SAD_ARCHITECTURE_REGISTER+".ipc";

    public final static String PACKAGE_SAD_ARCHITECTURE_REGISTER_IPC_SUBSCRIPTION=PACKAGE_SAD_ARCHITECTURE_REGISTER_IPC+".subscription";*/

}
